name: check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: vulnerbility_check
        run: bash go-test.sh -v pkg/zhmcclient

      - name: unit-test
        run: bash go-test.sh -p pkg/zhmcclient